bioinformatics wiki
mendelics/awesome pull request #1
Opened 2020-04-17 20:15 UTC by diegomscoelho

## Descrição

Material sobre bioinformática, genômica, genética mendeliana, genética humana, etc.
Criar um pequeno compêndio que poderá ser consultado pela equipe.

2020-04-22 12:07 UTC, ggabriel96 requested changes
Detalhezinhos bobos

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +### Este documento contém materiais recomendados pela equipe de desenvolvimento da mendelics
```suggestion
### Este documento contém materiais recomendados pela equipe de desenvolvimento da Mendelics
```

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +](https://www.youtube.com/watch?v=8kK2zwjRV0M)
```suggestion
    - [DNA Structure and Replication: Crash Course Biology #10](https://www.youtube.com/watch?v=8kK2zwjRV0M)
```

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +](https://www.youtube.com/watch?v=itsb2SqR-R0)
```suggestion
    - [DNA, Hot Pockets, & The Longest Word Ever: Crash Course Biology #11](https://www.youtube.com/watch?v=itsb2SqR-R0)
```

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +](https://youtu.be/AmOO4j0E408)
```suggestion
    - [DNA | Biomolecules | MCAT | Khan Academy](https://youtu.be/AmOO4j0E408)
```

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +](https://github.com/gatk-workflows/)
```suggestion
    - [GATK workflows](https://github.com/gatk-workflows/)
```

2020-04-22 12:07 UTC, ggabriel96 commented on README.md
> +](https://github.com/gatk-workflows/gatk4-genome-processing-pipeline)
```suggestion
        - [gatk4-genome-processing-pipeline](https://github.com/gatk-workflows/gatk4-genome-processing-pipeline)
```

2020-04-22 12:09 UTC, ggabriel96 commented on README.md
> +### Este documento contém materiais recomendados pela equipe de desenvolvimento da mendelics
E aqui, talvez mais uma questão de gosto, eu achei melhor deixar a descrição no mesmo nível do sumário e o texto da descrição sem nenhuma ênfase, e.g.

```markdown
# Descrição

Este documento...
```

2020-04-22 12:09 UTC, ggabriel96 commented on README.md
> +1. [MOOC](#mooc)
:+1: pro uso dos links com as âncoras :D

2020-04-22 15:41 UTC, diegomscoelho commented on README.md
> +### Este documento contém materiais recomendados pela equipe de desenvolvimento da mendelics
Também achei melhor

2020-04-22 15:43 UTC, diegomscoelho commented
Detalhe bobo nada. Ficou bem melhor.

2020-04-22 17:42 UTC, diegomscoelho reviewed
Detalhe bobo nada. Ficou bem melhor.

2020-04-22 20:58 UTC, ggabriel96 commented on README.md
> +### Este documento contém materiais recomendados pela equipe de desenvolvimento da mendelics
Blz hahaha. Mas o `Este documento contém materiais recomendados pela equipe de desenvolvimento da Mendelics` continua com `###`?

2020-04-23 14:50 UTC, diegomscoelho commented on README.md
> +### Este documento contém materiais recomendados pela equipe de desenvolvimento da mendelics
Feito!

2020-04-23 16:40 UTC, ggabriel96 approved these changes

2020-04-23 16:40 UTC, merged